# Generated by Django 3.2.13 on 2022-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
