# Generated by Django 3.2.13 on 2022-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclothcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='sanjay', upload_to='images'),
            preserve_default=False,
        ),
    ]
